### ISSUE TITLE
Can you fixed this error?

### ISSUE THREAD

**Issue by tinhlam1205** [Darionu/CMS#1]
Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/profile/gal."

**Comment by Darionu** [comment]
Hey,

There was a problem with the iron-router's old dependencies.
I added iron:middleware-stack with a version of 1.1.0 and it fixed the problem.

**Comment by tinhlam1205** [comment]
Thank you! I fixed the problem!

**Comment by tinhlam1205** [comment]
Ah! I try to show the all post of member, but I can not do it.
May I help you the code?

**Comment by Darionu** [comment]
The list can be quite long.
What do you think of listing the last 5posts and then make another template for a list of all the posts from an user? The project is old but I don't mind to do some improvements in it.

 If you have any good ideas tell me 👍

**Comment by tinhlam1205** [comment]
I try make a template for a list of all the posts from an user.
     list of all the posts from an user Posts: function(){
           return posts.find({**??**},{sort: {date:**???**);
       },
My last question (**I'm not good at meteor)**  
Thank you for you help!

**Comment by Darionu** [comment]
Sorry I'm a bit busy recently..
I pushed a new commit with showing 5 recent posts of the user.
Maybe you will get some ideas by looking at the code.

If you want to get posts only from a selected user then your query needs to be like this:
`posts.find({ author: authorId });`

You can pass authorId or username (You will need to get id later using it) in router url as param.
